[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force all redirects to be handled by Next.js
# The plugin handles this automatically so we don't need manual redirects